"""Render the README charts from the dbt marts.

Run after `dbt build`. Reads the DuckDB file produced by dbt and writes PNGs to docs/images.

Usage:
    python scripts/make_charts.py --db dbt/wvphn.duckdb --out docs/images
"""

import argparse
from pathlib import Path

import duckdb
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

# Validated categorical palette (fixed order) and reserved status colours
BLUE, ORANGE, AQUA, YELLOW = "#2a78d6", "#eb6834", "#1baf7a", "#eda100"
CRITICAL = "#d03b3b"
INK, INK_2, MUTED, GRID, AXIS, SURFACE = "#0b0b0b", "#52514e", "#898781", "#e1e0d9", "#c3c2b7", "#fcfcfb"
SUBREGION_COLOURS = {
    "Geelong Otway": BLUE,
    "Ballarat Goldfields": ORANGE,
    "Great South Coast": AQUA,
    "Wimmera Grampians": YELLOW,
}

plt.rcParams.update(
    {
        "font.family": "DejaVu Sans",
        "font.size": 10,
        "axes.edgecolor": AXIS,
        "axes.labelcolor": INK_2,
        "axes.titlecolor": INK,
        "axes.titlesize": 11,
        "axes.titleweight": "bold",
        "axes.spines.top": False,
        "axes.spines.right": False,
        "xtick.color": MUTED,
        "ytick.color": INK_2,
        "figure.facecolor": SURFACE,
        "axes.facecolor": SURFACE,
        "savefig.facecolor": SURFACE,
        "grid.color": GRID,
        "grid.linewidth": 0.8,
    }
)


def source_note(fig, text):
    fig.text(0.01, 0.01, text, fontsize=8, color=MUTED, ha="left", va="bottom")


def scorecard(con, out):
    df = con.sql(
        """select provider_label, median_days_to_first_contact as wait, followup_7day_rate as fu7,
                  outcome_collection_rate as out3, wait_status, followup_status, outcome_collection_status
           from marts.kpi_provider_scorecard order by provider_code desc"""
    ).df()
    panels = [
        ("wait", "wait_status", "Median days to first contact", 14, "Target ≤ 14 days", lambda v: f"{v:.0f}"),
        ("fu7", "followup_status", "Suicide risk referrals seen in 7 days", 0.80, "Target ≥ 80%", lambda v: f"{v:.0%}"),
        ("out3", "outcome_collection_status", "Episodes with start and end outcome", 0.70, "Target ≥ 70%", lambda v: f"{v:.0%}"),
    ]
    fig, axes = plt.subplots(1, 3, figsize=(14, 4.8), sharey=True)
    for ax, (col, status, title, target, tlabel, fmt) in zip(axes, panels):
        colours = [CRITICAL if s == "Below target" else BLUE for s in df[status]]
        ax.barh(df.provider_label, df[col], color=colours, height=0.62)
        ax.axvline(target, color=INK_2, linestyle=(0, (3, 3)), linewidth=1)
        ax.text(target, -0.75, f" {tlabel}", color=INK_2, fontsize=8, va="top")
        for i, (v, s) in enumerate(zip(df[col], df[status])):
            label = fmt(v) + ("  below target" if s == "Below target" else "")
            ax.text(v, i, f" {label}", va="center", fontsize=8.5, color=INK if s == "Below target" else INK_2,
                    bbox=dict(facecolor=SURFACE, edgecolor="none", pad=0.5), zorder=4)
        ax.set_title(title, loc="left", fontsize=10)
        ax.xaxis.grid(True)
        ax.set_axisbelow(True)
        ax.tick_params(axis="y", length=0)
        ax.set_ylim(-1.3, len(df) - 0.5)
        if col == "wait":
            ax.set_xlim(0, 32)
            ax.set_xticks([0, 7, 14, 21, 28])
        else:
            ax.set_xlim(0, 1.45)
            ax.set_xticks([0, 0.25, 0.5, 0.75, 1.0])
            ax.xaxis.set_major_formatter(matplotlib.ticker.PercentFormatter(1.0, decimals=0))
    fig.suptitle("Provider scorecard, January to June 2026", x=0.01, ha="left", fontsize=13, fontweight="bold", color=INK)
    source_note(fig, "SYNTHETIC provider data generated by scripts/generate_synthetic_data.py. Source model: marts.kpi_provider_scorecard")
    fig.tight_layout(rect=(0, 0.04, 1, 0.95))
    fig.savefig(out / "provider_scorecard.png", dpi=150)
    plt.close(fig)


def outcome_trend(con, out):
    df = con.sql(
        """select provider_code, quarter, quarter_label, outcome_collection_rate as rate
           from marts.kpi_provider_quarterly
           where quarter >= date '2025-04-01' and episodes_completed >= 20
           order by quarter"""
    ).df()
    fig, ax = plt.subplots(figsize=(9, 4.6))
    highlight = {"GS-01": BLUE, "WG-01": ORANGE}
    for code, g in df.groupby("provider_code"):
        if code in highlight:
            continue
        ax.plot(g.quarter_label, g.rate, color=AXIS, linewidth=1.2, zorder=1)
    for code, colour in highlight.items():
        g = df[df.provider_code == code]
        ax.plot(g.quarter_label, g.rate, color=colour, linewidth=2.2, marker="o", markersize=6, label=code, zorder=3)
        ax.text(len(g) - 1 + 0.08, g.rate.iloc[-1], f"{code} {g.rate.iloc[-1]:.0%}", color=INK, va="center", fontsize=9)
    ax.plot([], [], color=AXIS, linewidth=1.2, label="Other providers")
    ax.axhline(0.70, color=INK_2, linestyle=(0, (3, 3)), linewidth=1)
    ax.text(0, 0.705, "Target 70%", color=INK_2, fontsize=8, va="bottom")
    ax.set_ylim(0, 1)
    ax.yaxis.set_major_formatter(matplotlib.ticker.PercentFormatter(1.0, decimals=0))
    ax.yaxis.grid(True)
    ax.set_axisbelow(True)
    ax.set_xlim(-0.2, len(df.quarter_label.unique()) - 0.2)
    ax.legend(frameon=False, loc="lower right", fontsize=9)
    ax.set_title("Outcome measure collection by episode end quarter", loc="left")
    source_note(fig, "SYNTHETIC. GS-01 process fix from March 2026 is visible in 2026-Q2. Source model: marts.kpi_provider_quarterly")
    fig.tight_layout(rect=(0, 0.04, 1, 1))
    fig.savefig(out / "outcome_collection_trend.png", dpi=150)
    plt.close(fig)


def ed_benchmark(con, out):
    df = con.sql("select financial_year, wvphn_rate, national_rate from marts.lower_urgency_ed_benchmark order by fy_end_year").df()
    fig, ax = plt.subplots(figsize=(9, 4.6))
    for col, colour, name in [("national_rate", ORANGE, "Australia"), ("wvphn_rate", BLUE, "Western Victoria PHN")]:
        ax.plot(df.financial_year, df[col], color=colour, linewidth=2.2, marker="o", markersize=6, label=name)
        ax.text(len(df) - 1 + 0.1, df[col].iloc[-1], f"{name}\n{df[col].iloc[-1]:.1f}", color=INK, va="center", fontsize=9)
    ax.set_ylim(0, max(df.national_rate.max(), df.wvphn_rate.max()) * 1.15)
    ax.set_xlim(-0.3, len(df) + 0.9)
    ax.yaxis.grid(True)
    ax.set_axisbelow(True)
    ax.set_ylabel("Presentations per 1,000 (age-standardised)")
    ax.legend(frameon=False, loc="lower left", fontsize=9)
    ax.set_title("Lower urgency ED presentations (triage 4 and 5), all hours", loc="left")
    source_note(fig, "REAL data. AIHW, Use of emergency departments for lower urgency care 2017-18 to 2024-25. Source model: marts.lower_urgency_ed_benchmark")
    fig.tight_layout(rect=(0, 0.04, 1, 1))
    fig.savefig(out / "lower_urgency_ed_benchmark.png", dpi=150)
    plt.close(fig)


def ed_sa3(con, out):
    df = con.sql(
        """select sa3_name, subregion, rate_age_standardised as rate, financial_year
           from marts.lower_urgency_ed_sa3
           where fy_end_year = (select max(fy_end_year) from marts.lower_urgency_ed_sa3)
           order by rate"""
    ).df()
    national = con.sql(
        "select national_rate from marts.lower_urgency_ed_benchmark order by fy_end_year desc limit 1"
    ).fetchone()[0]
    fig, ax = plt.subplots(figsize=(9, 5))
    ax.barh(df.sa3_name, df.rate, color=[SUBREGION_COLOURS[s] for s in df.subregion], height=0.62)
    for i, v in enumerate(df.rate):
        ax.text(v, i, f" {v:.0f}", va="center", fontsize=8.5, color=INK_2)
    ax.axvline(national, color=INK_2, linestyle=(0, (3, 3)), linewidth=1)
    ax.text(national, len(df) - 0.4, f" Australia {national:.0f}", color=INK_2, fontsize=8, va="bottom")
    handles = [plt.Rectangle((0, 0), 1, 1, color=c) for c in SUBREGION_COLOURS.values()]
    ax.legend(handles, SUBREGION_COLOURS.keys(), frameon=False, loc="lower right", fontsize=9, title="WVPHN subregion", title_fontsize=9)
    ax.xaxis.grid(True)
    ax.set_axisbelow(True)
    ax.tick_params(axis="y", length=0)
    ax.set_xlabel("Presentations per 1,000 (age-standardised)")
    ax.set_title(f"Lower urgency ED use by SA3, {df.financial_year.iloc[0]}", loc="left")
    source_note(fig, "REAL data. AIHW. SA3 to subregion mapping from the WVPHN Health Needs Assessment. Source model: marts.lower_urgency_ed_sa3")
    fig.tight_layout(rect=(0, 0.04, 1, 1))
    fig.savefig(out / "lower_urgency_ed_sa3.png", dpi=150)
    plt.close(fig)


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--db", default="dbt/wvphn.duckdb")
    parser.add_argument("--out", default="docs/images")
    args = parser.parse_args()
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    con = duckdb.connect(args.db, read_only=True)
    for chart in (scorecard, outcome_trend, ed_benchmark, ed_sa3):
        chart(con, out)
    print(f"charts written to {out}")


if __name__ == "__main__":
    main()
